In [17]:
import pandas as pd
import numpy as np


df=pd.DataFrame({
    "A" : np.append(np.zeros(10), np.ones(10)),
    "B" : np.append(np.zeros(10), np.ones(10))
})

In [18]:
df

     A    B
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0
3  0.0  0.0
4  0.0  0.0
5  0.0  0.0
6  0.0  0.0
7  0.0  0.0
8  0.0  0.0
9  0.0  0.0

In [19]:
import pandas as pd

row = 0
while row < len(df) - 1:
    current_ = df.iloc[row]
    forward_ = df.iloc[row + 1]
    if (current_ == forward_).all():
        df.drop(index=row + 1, inplace=True)
        df.reset_index(drop=True, inplace=True)  # Reset index after drop
    else:
        row += 1

In [20]:
df

     A    B
0  0.0  0.0